### ISSUE TITLE
Desktop H1 issue

### ISSUE THREAD

**Issue by mrcwinn** [Rewinn/Saab-Site#2]
On my laptop, the H1 position is jacked.

![screen shot 2015-04-30 at 10 29 47 pm](https://cloud.githubusercontent.com/assets/1095854/7425928/865eb502-ef88-11e4-9f2d-16dd9c43e961.png)

**Comment by Rewinn** [comment]
Fixed Safari issue. There seems to be issues with Safari and text-transform.  From what I read, it looks like Chrome used to have a similar bug, but it has been resolved.

New code: 
h1 {
  letter-spacing: -4px;
  word-spacing: 4px;
  width: 100%;
  color: #BEB735;
  font-size: 4vmax;
  font-family: 'Quicksand', sans-serif;
  font-weight: 400;
  position: absolute;
  top: 5%;
  margin: 0;
  text-align: center;
}
